# -*- coding: utf-8 -*-
"""Brain_MedSam

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q6DW2Kv9TDMkbbSMeZZxr6KeDZZSlmGU
"""

# import needed libraries

# Part 1: Setup and Data Loading for Brain Segmentation with MedSAM
# Run this in Google Colab

import os
import sys
import urllib.request
import tarfile
import zipfile
import json
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import nibabel as nib
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

print("🚀 Part 1: Setting up Brain Segmentation with MedSAM")
print("="*60)

# ============================================================================
# STEP 1: Install Required Packages
# ============================================================================

def install_requirements():
    """Install all required packages for the project"""

    packages = [
        'nibabel',                    # For medical image processing
        'scikit-image',              # Image processing
        'opencv-python',             # Computer vision
        'plotly',                    # 3D visualization
        'ipywidgets',                # Interactive widgets
        'torch torchvision',         # PyTorch
        'monai',                     # Medical imaging AI
        'vtk',                       # 3D visualization
        'pyvista',                   # 3D mesh processing
        'trimesh',                   # 3D geometry
        'pillow',                    # Image handling
        'scipy',                     # Scientific computing
        'segment-anything',          # SAM base model
        'git+https://github.com/bowang-lab/MedSAM.git'  # MedSAM
    ]

    print("📦 Installing required packages...")
    for package in packages:
        try:
            os.system(f'pip install -q {package}')
            print(f"✅ Installed: {package}")
        except:
            print(f"⚠️ Failed to install: {package}")

# Uncomment the next line to install packages
# install_requirements()

# ============================================================================
# STEP 2: Setup Directories
# ============================================================================

def setup_directories():
    """Create project directory structure"""

    base_dir = Path("/content/brain_segmentation")
    dirs = {
        'base': base_dir,
        'data': base_dir / "data",
        'models': base_dir / "models",
        'results': base_dir / "results",
        'visualizations': base_dir / "visualizations",
        'checkpoints': base_dir / "checkpoints"
    }

    for name, path in dirs.items():
        path.mkdir(parents=True, exist_ok=True)
        print(f"✅ Created: {path}")

    return dirs

# Setup directories
directories = setup_directories()

# ============================================================================
# STEP 3: Download and Extract Dataset
# ============================================================================

def download_dataset(data_dir):
    """Download MRBrainS13 dataset"""

    url = "https://dataverse.nl/api/access/dataset/:persistentId/?persistentId=doi:10.34894/645ZIN"
    download_path = data_dir / "MRBrainS13_download"

    print("📥 Downloading brain dataset...")
    try:
        # Download the file
        urllib.request.urlretrieve(url, download_path)
        print(f"✅ Downloaded to: {download_path}")

        # Check the file type by reading first few bytes
        with open(download_path, 'rb') as f:
            header = f.read(512)

        # Determine file type and rename accordingly
        if header.startswith(b'PK'):
            # ZIP file
            final_path = data_dir / "MRBrainS13.zip"
            download_path.rename(final_path)
            print(f"📦 Detected: ZIP archive")
            return final_path
        elif header[257:262] == b'ustar':
            # TAR file
            final_path = data_dir / "MRBrainS13.tar"
            download_path.rename(final_path)
            print(f"📦 Detected: TAR archive")
            return final_path
        elif header.startswith(b'\x1f\x8b'):
            # GZIP file
            final_path = data_dir / "MRBrainS13.tar.gz"
            download_path.rename(final_path)
            print(f"📦 Detected: GZIP archive")
            return final_path
        else:
            # Unknown format - might be HTML or error page
            print(f"⚠️ Unknown file format. First 100 bytes:")
            print(header[:100])
            return None

    except Exception as e:
        print(f"❌ Download failed: {e}")
        return None

def extract_dataset(archive_path, data_dir):
    """Extract the dataset"""

    if not archive_path or not archive_path.exists():
        return None

    print("📂 Extracting dataset...")
    try:
        # Determine extraction method based on file extension
        if archive_path.suffix == '.zip':
            with zipfile.ZipFile(archive_path, 'r') as zip_ref:
                zip_ref.extractall(data_dir)
            # Check if there are nested zip files and extract them
            for item in data_dir.iterdir():
                if item.is_file() and item.suffix == '.zip' and item.name != archive_path.name:
                    print(f"  Nested ZIP found: {item.name}. Extracting...")
                    with zipfile.ZipFile(item, 'r') as nested_zip_ref:
                        nested_zip_ref.extractall(data_dir)
                    item.unlink() # Remove the nested zip file after extraction
        elif archive_path.suffix == '.gz':
            with tarfile.open(archive_path, 'r:gz') as tar:
                tar.extractall(data_dir)
        elif archive_path.suffix == '.tar':
            with tarfile.open(archive_path, 'r:') as tar:
                tar.extractall(data_dir)
        else:
            print(f"❌ Unsupported archive format: {archive_path.suffix}")
            return None

        # Find the extracted directory
        extracted_path = data_dir / "MRBrainS13"
        if extracted_path.exists():
            print(f"✅ Extracted to: {extracted_path}")
            return extracted_path

        # Check for common MRBrainS dataset folder names
        possible_names = ['MRBrainS13DataNii', 'TrainingData', 'training', 'MRBrainS']
        for name in possible_names:
            check_path = data_dir / name
            if check_path.exists():
                print(f"✅ Extracted to: {check_path}")
                return check_path

        # Check what was actually extracted
        for item in data_dir.iterdir():
            if item.is_dir() and item.name not in ['__pycache__', 'models', 'results', 'visualizations', 'checkpoints', '.ipynb_checkpoints']:
                print(f"✅ Extracted to: {item}")
                return item

        # If nothing found, return data_dir itself
        print(f"⚠️ No specific subdirectory found, using: {data_dir}")
        return data_dir


    except Exception as e:
        print(f"❌ Error extracting: {e}")
        return None


# Download and extract
dataset_file = download_dataset(directories['data'])
dataset_path = extract_dataset(dataset_file, directories['data'])

# ============================================================================
# STEP 4: Explore Dataset Structure
# ============================================================================

def explore_dataset(dataset_path):
    """Explore the dataset structure and load configuration"""

    if not dataset_path or not dataset_path.exists():
        print("❌ Dataset path not found!")
        return None, None

    print("\n📋 Exploring MRBrainS13 Dataset Structure...")

    # Find all NIfTI files
    nii_files = list(dataset_path.rglob("*.nii")) + list(dataset_path.rglob("*.nii.gz"))
    print(f"   Found {len(nii_files)} NIfTI files")

    # Display directory structure
    print(f"\n📁 Directory structure:")
    for item in dataset_path.rglob("*"):
        if item.is_dir():
            level = len(item.relative_to(dataset_path).parts)
            indent = "   " * level
            print(f"{indent}📁 {item.name}")

    # Try to find training data patterns
    dataset_info = {}

    # Look for subject folders
    subject_folders = []
    for item in dataset_path.iterdir():
        if item.is_dir() and item.name not in ['__pycache__', '.ipynb_checkpoints']:
            subject_folders.append(item)

    # Check for MRBrainS typical structure
    subdirs = ['imagesTr', 'labelsTr', 'imagesTs', 'TrainingData', 'training']
    for subdir in subdirs:
        subdir_path = dataset_path / subdir
        if subdir_path.exists():
            files = list(subdir_path.glob("*.nii.gz")) + list(subdir_path.glob("*.nii"))
            dataset_info[subdir] = {
                'path': subdir_path,
                'files': files,
                'count': len(files)
            }
            print(f"   📁 {subdir}: {len(files)} files")

    # If no standard structure, look for subject-based structure
    if not dataset_info and subject_folders:
        print(f"\n   Found {len(subject_folders)} subject folders:")
        images = []
        labels = []

        for subject in subject_folders:
            print(f"   📁 {subject.name}")
            subj_files = list(subject.glob("*.nii*"))

            for f in subj_files:
                if 'seg' in f.name.lower() or 'label' in f.name.lower():
                    labels.append(f)
                else:
                    images.append(f)

        dataset_info['imagesTr'] = {
            'path': dataset_path,
            'files': images,
            'count': len(images)
        }
        dataset_info['labelsTr'] = {
            'path': dataset_path,
            'files': labels,
            'count': len(labels)
        }
        dataset_info['imagesTs'] = {'path': None, 'files': [], 'count': 0}

        print(f"\n   📊 Found {len(images)} training images")
        print(f"   📊 Found {len(labels)} label files")

    # Create a basic config
    config = {
        'name': 'MRBrainS13',
        'description': 'Brain MRI Segmentation',
        'modality': 'MRI',
        'numTraining': dataset_info.get('imagesTr', {}).get('count', 0),
        'numTest': dataset_info.get('imagesTs', {}).get('count', 0),
        'labels': {
            '0': 'Background',
            '1': 'Grey Matter',
            '2': 'White Matter',
            '3': 'CSF'
        }
    }

    return dataset_info, config

# Explore dataset
if dataset_path:
    dataset_info, dataset_config = explore_dataset(dataset_path)

    # Save paths for next parts
    if dataset_info: # Check if dataset_info is not empty
        with open(directories['base'] / 'paths.json', 'w') as f:
            json.dump({
                'dataset_path': str(dataset_path),
                'directories': {k: str(v) for k, v in directories.items()},
                'train_images': len(dataset_info.get('imagesTr', {}).get('files', [])) if 'imagesTr' in dataset_info else 0,
                'train_labels': len(dataset_info.get('labelsTr', {}).get('files', [])) if 'labelsTr' in dataset_info else 0,
                'model_type': 'medsam'
            }, f, indent=2)

        print(f"\n🎉 Part 1 Complete!")
        print(f"✅ Dataset ready with {dataset_info.get('imagesTr', {}).get('count', 0)} training images")
        print(f"📍 All paths saved to: {directories['base'] / 'paths.json'}")
        print(f"🤖 Model: MedSAM (Medical Segment Anything Model)")

    else:
        print("❌ Failed to setup dataset. Please check the download URL and extracted file structure.")

else:
    print("❌ Failed to setup dataset. Please check the download URL.")

print("\n🎯 Next: Run Part 2 - Data Preprocessing and MedSAM Model Setup")

# Part 2: Data Preprocessing and MedSAM Model Setup
# Run after Part 1

import numpy as np
import matplotlib.pyplot as plt
import nibabel as nib
from pathlib import Path
import json
from skimage import measure, filters
from scipy import ndimage
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import torch
import torch.nn as nn
from PIL import Image
import cv2

# Import MedSAM
from segment_anything import sam_model_registry
from segment_anything.utils.transforms import ResizeLongestSide

print("🚀 Part 2: Data Preprocessing and MedSAM Model Setup")
print("="*50)

# Load paths from Part 1
with open('/content/brain_segmentation/paths.json', 'r') as f:
    paths_info = json.load(f)

dataset_path = Path(paths_info['dataset_path'])
directories = {k: Path(v) for k, v in paths_info['directories'].items()}

# ============================================================================
# STEP 1: Data Loading and Preprocessing Functions
# ============================================================================

def load_nifti_data(image_path, label_path=None):
    """Load NIfTI image and optional label"""

    # Load image
    image_nii = nib.load(image_path)
    image_data = image_nii.get_fdata()

    result = {
        'image': image_data,
        'image_nii': image_nii,
        'spacing': image_nii.header.get_zooms(),
        'affine': image_nii.affine
    }

    # Load label if provided
    if label_path and Path(label_path).exists():
        label_nii = nib.load(label_path)
        label_data = label_nii.get_fdata()
        result['label'] = label_data
        result['label_nii'] = label_nii

    return result

def preprocess_image(image_data, percentile_lower=1, percentile_upper=99):
    """Apply MRI intensity normalization"""

    # Normalize MRI intensity using percentiles
    lower = np.percentile(image_data, percentile_lower)
    upper = np.percentile(image_data, percentile_upper)

    # Clip and normalize
    clipped = np.clip(image_data, lower, upper)
    normalized = (clipped - lower) / (upper - lower)

    return normalized

def preprocess_for_medsam(image_slice, target_size=1024):
    """Preprocess a single 2D slice for MedSAM input"""

    # Normalize to 0-255 range
    img_normalized = (image_slice - image_slice.min()) / (image_slice.max() - image_slice.min() + 1e-8)
    img_uint8 = (img_normalized * 255).astype(np.uint8)

    # Convert to 3-channel (MedSAM expects RGB input)
    rgb_image = np.stack([img_uint8, img_uint8, img_uint8], axis=-1)

    # Resize to target size (MedSAM uses 1024x1024)
    h, w = rgb_image.shape[:2]
    if h > w:
        new_h = target_size
        new_w = int(w * target_size / h)
    else:
        new_w = target_size
        new_h = int(h * target_size / w)

    resized = cv2.resize(rgb_image, (new_w, new_h), interpolation=cv2.INTER_LINEAR)

    # Pad to square
    padded = np.zeros((target_size, target_size, 3), dtype=np.uint8)
    padded[:new_h, :new_w] = resized

    # Convert to tensor (C, H, W) and normalize
    tensor = torch.from_numpy(padded).float().permute(2, 0, 1)

    # MedSAM uses pixel mean and std normalization
    pixel_mean = torch.tensor([123.675, 116.28, 103.53]).view(-1, 1, 1)
    pixel_std = torch.tensor([58.395, 57.12, 57.375]).view(-1, 1, 1)
    tensor = (tensor - pixel_mean) / pixel_std

    return tensor, padded, (new_h, new_w)

def preprocess_label(label_slice, target_size=(1024, 1024)):
    """Preprocess label for MedSAM training"""

    # Resize label using nearest neighbor to preserve class values
    resized = cv2.resize(label_slice.astype(np.float32), target_size,
                        interpolation=cv2.INTER_NEAREST)

    return torch.from_numpy(resized).long()

def get_bounding_box_prompt(label_slice, class_id):
    """Generate bounding box prompt from ground truth label for a specific class"""

    mask = (label_slice == class_id).astype(np.uint8)

    if not np.any(mask):
        return None

    # Find bounding box
    rows = np.any(mask, axis=1)
    cols = np.any(mask, axis=0)

    if not np.any(rows) or not np.any(cols):
        return None

    rmin, rmax = np.where(rows)[0][[0, -1]]
    cmin, cmax = np.where(cols)[0][[0, -1]]

    # Format: [x_min, y_min, x_max, y_max]
    bbox = np.array([cmin, rmin, cmax, rmax])

    return bbox

def identify_brain_parts(label_data):
    """Identify different parts of brain segmentation"""

    unique_labels = np.unique(label_data)
    print(f"📊 Found labels: {unique_labels}")

    # For MRBrainS13: 0=background, 1=grey matter, 2=white matter, 3=CSF
    parts = {
        0: {'name': 'Background', 'color': 'rgba(0,0,0,0)'},
        1: {'name': 'Grey Matter', 'color': 'rgba(128,128,128,0.7)'},     # Gray
        2: {'name': 'White Matter', 'color': 'rgba(255,255,255,0.7)'},    # White
        3: {'name': 'CSF', 'color': 'rgba(0,191,255,0.7)'}                # Deep Sky Blue
    }

    return parts, unique_labels

# ============================================================================
# STEP 2: Load MedSAM Model
# ============================================================================

def download_medsam_checkpoint(checkpoint_path):
    """Download MedSAM checkpoint"""

    # Check if file exists and is valid
    if checkpoint_path.exists():
        # Verify it's a valid checkpoint by checking file size and header
        file_size = checkpoint_path.stat().st_size
        if file_size > 100_000_000:  # Should be around 2.4GB
            print(f"✅ Using existing checkpoint: {checkpoint_path}")
            return True
        else:
            print(f"⚠️ Existing file seems corrupted (size: {file_size/1e6:.1f}MB), removing...")
            checkpoint_path.unlink()

    print("📥 Downloading MedSAM checkpoint (2.4GB)...")
    print("   Using gdown for Google Drive download...")

    try:
        # Install gdown if not available
        import subprocess
        subprocess.run(['pip', 'install', '-q', 'gdown'], check=True)
        import gdown

        # Google Drive file ID for MedSAM
        file_id = "1UAmWL88roYR7wKlnApw5Bcuzf2iQgk6_"
        url = f"https://drive.google.com/uc?id={file_id}"

        gdown.download(url, str(checkpoint_path), quiet=False)

        # Verify download
        if checkpoint_path.exists() and checkpoint_path.stat().st_size > 100_000_000:
            print(f"✅ Downloaded to: {checkpoint_path}")
            return True
        else:
            print("❌ Download failed or file is corrupted")
            return False

    except Exception as e:
        print(f"❌ Download failed: {e}")
        print("\n📝 Please download manually:")
        print("   1. Visit: https://drive.google.com/file/d/1UAmWL88roYR7wKlnApw5Bcuzf2iQgk6_/view")
        print("   2. Download the file")
        print(f"   3. Upload it to: {checkpoint_path}")
        print("\n   Or run this command:")
        print(f"   !gdown 1UAmWL88roYR7wKlnApw5Bcuzf2iQgk6_ -O {checkpoint_path}")
        return False

def load_medsam_model(checkpoint_path, model_type='vit_b'):
    """Load MedSAM model"""

    print("🤖 Loading MedSAM model...")

    # Download checkpoint if needed
    if not download_medsam_checkpoint(checkpoint_path):
        print("⚠️ Using SAM base model instead (not fine-tuned for medical images)")
        # Fallback to base SAM if download fails
        model_type = 'vit_b'

    # Initialize model
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Load SAM model
    sam_model = sam_model_registry[model_type]()

    # Load MedSAM checkpoint if available
    if checkpoint_path.exists():
        print(f"📂 Loading checkpoint from: {checkpoint_path}")
        checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
        sam_model.load_state_dict(checkpoint, strict=True)
        print("✅ Loaded MedSAM checkpoint")
    else:
        print("⚠️ Checkpoint not found, using base SAM")

    sam_model = sam_model.to(device)
    sam_model.eval()

    print(f"✅ Model loaded on: {device}")
    print(f"   Model type: MedSAM ({model_type})")
    print(f"   Input size: 1024x1024")
    print(f"   Prompt type: Bounding box for each brain region")

    return sam_model, device

# Load MedSAM model
medsam_checkpoint = directories['models'] / 'medsam_vit_b.pth'
medsam_model, device = load_medsam_model(medsam_checkpoint, model_type='vit_b')

# Save model info
model_info = {
    'model_type': 'medsam_vit_b',
    'num_classes': 4,
    'input_size': [1024, 1024],
    'device': str(device),
    'checkpoint': str(medsam_checkpoint),
    'prompt_type': 'bounding_box'
}

with open(directories['models'] / 'model_config.json', 'w') as f:
    json.dump(model_info, f, indent=2)

# ============================================================================
# STEP 3: Load and Visualize Sample Data
# ============================================================================

def load_sample_case(dataset_path, case_index=0):
    """Load a sample case for demonstration"""

    print(f"🔍 Exploring dataset structure at: {dataset_path}")

    # Check if dataset_path itself is the training directory (contains subject folders)
    potential_subjects = [item for item in dataset_path.iterdir() if item.is_dir() and not item.name.startswith('.')]

    # If we find numbered folders or folders with subject data, use dataset_path directly
    if potential_subjects:
        # Check if these look like subject folders
        first_folder = potential_subjects[0]
        nii_files = list(first_folder.glob("*.nii*"))
        if nii_files:
            print(f"✅ Dataset path contains subject folders directly")
            training_dir = dataset_path
        else:
            # Look for TrainingData subfolder
            training_dir = dataset_path / "TrainingData"
    else:
        training_dir = dataset_path / "TrainingData"

    if not training_dir.exists():
        # Try alternative paths
        possible_dirs = ['TrainingData', 'training', 'train', 'Training']
        for dirname in possible_dirs:
            check_dir = dataset_path / dirname
            if check_dir.exists():
                training_dir = check_dir
                break

    print(f"✅ Using training directory: {training_dir}")

    # Find subject folders or NIfTI files
    subject_folders = sorted([f for f in training_dir.iterdir() if f.is_dir() and not f.name.startswith('.')])

    if not subject_folders:
        print("⚠️ No subject folders found")
        return None

    print(f"✅ Found {len(subject_folders)} subject folders: {[f.name for f in subject_folders]}")

    # Select case
    if case_index >= len(subject_folders):
        case_index = 0

    subject_folder = subject_folders[case_index]
    print(f"\n📁 Loading case {case_index}: {subject_folder.name}")

    # Find image and label files - look for segmentation files
    all_files = list(subject_folder.iterdir())
    print(f"   📂 Files in subject folder: {[f.name for f in all_files]}")

    # MRBrainS13 typically has segmentation files, look for them
    image_files = [f for f in all_files if f.suffix in ['.nii', '.gz'] and 'seg' not in f.name.lower() and 'label' not in f.name.lower()]
    label_files = [f for f in all_files if f.suffix in ['.nii', '.gz'] and ('seg' in f.name.lower() or 'label' in f.name.lower() or 'labelsfor' in f.name.lower())]

    # If no label files found with those patterns, check if there's a LabelsForTesting or similar
    if not label_files:
        # Look in parent directory for labels
        parent_labels = list(training_dir.glob(f"*{subject_folder.name}*.nii*"))
        parent_labels += list(training_dir.parent.glob(f"*{subject_folder.name}*.nii*"))
        label_files = [f for f in parent_labels if 'label' in f.name.lower() or 'seg' in f.name.lower()]

    if not image_files:
        print("❌ No image files found!")
        print(f"   Searched in: {subject_folder}")
        print(f"   Files present: {[f.name for f in subject_folder.iterdir()]}")
        return None

    if not label_files:
        print("❌ No label files found!")
        print(f"   Searched in: {subject_folder}")
        print(f"   Files present: {[f.name for f in subject_folder.iterdir()]}")
        return None

    image_path = image_files[0]
    label_path = label_files[0]

    print(f"   📄 Image: {image_path.name}")
    print(f"   📄 Label: {label_path.name}")

    # Load data
    data = load_nifti_data(image_path, label_path)

    # Preprocess
    data['image_processed'] = preprocess_image(data['image'])

    # Identify brain parts
    data['parts'], data['unique_labels'] = identify_brain_parts(data['label'])

    # Print info
    print(f"   📊 Image shape: {data['image'].shape}")
    print(f"   📊 Spacing: {data['spacing']}")
    print(f"   📊 Value range: {data['image'].min():.1f} to {data['image'].max():.1f}")
    print(f"   🎯 Labels found: {data['unique_labels']}")

    return data

# Load sample case
sample_data = load_sample_case(dataset_path, case_index=0)

# ============================================================================
# STEP 4: Test MedSAM on Sample Slice
# ============================================================================

def test_medsam_inference(model, device, image_slice, label_slice):
    """Test MedSAM inference on a sample slice with bounding box prompts"""

    print("🔬 Testing MedSAM inference on sample slice...")

    # Preprocess image
    input_tensor, padded_img, (new_h, new_w) = preprocess_for_medsam(image_slice)
    input_batch = input_tensor.unsqueeze(0).to(device)

    # Get image embeddings
    with torch.no_grad():
        image_embedding = model.image_encoder(input_batch)

    # Initialize prediction
    prediction = np.zeros((1024, 1024), dtype=np.uint8)

    # Segment each class separately using bounding box prompts
    for class_id in [1, 2, 3]:  # Grey matter, White matter, CSF
        # Get bounding box from ground truth
        bbox = get_bounding_box_prompt(label_slice, class_id)

        if bbox is not None:
            # Scale bbox to 1024x1024
            h_scale = new_h / image_slice.shape[0]
            w_scale = new_w / image_slice.shape[1]
            bbox_scaled = bbox.copy()
            bbox_scaled[0] *= w_scale  # x_min
            bbox_scaled[1] *= h_scale  # y_min
            bbox_scaled[2] *= w_scale  # x_max
            bbox_scaled[3] *= h_scale  # y_max

            # Prepare prompt
            box_torch = torch.as_tensor(bbox_scaled, dtype=torch.float, device=device)
            box_torch = box_torch.unsqueeze(0)  # Add batch dimension

            # Get mask prediction
            with torch.no_grad():
                sparse_embeddings, dense_embeddings = model.prompt_encoder(
                    points=None,
                    boxes=box_torch,
                    masks=None,
                )

                low_res_masks, _ = model.mask_decoder(
                    image_embeddings=image_embedding,
                    image_pe=model.prompt_encoder.get_dense_pe(),
                    sparse_prompt_embeddings=sparse_embeddings,
                    dense_prompt_embeddings=dense_embeddings,
                    multimask_output=False,
                )

                # Upscale and get binary mask
                masks = torch.nn.functional.interpolate(
                    low_res_masks,
                    size=(1024, 1024),
                    mode='bilinear',
                    align_corners=False
                )

                mask = masks[0, 0].cpu().numpy() > 0

                # Add to prediction
                prediction[mask] = class_id

    print(f"✅ Inference successful!")
    print(f"   Input shape: {input_batch.shape}")
    print(f"   Embedding shape: {image_embedding.shape}")
    print(f"   Prediction shape: {prediction.shape}")
    print(f"   Predicted classes: {np.unique(prediction)}")

    return prediction

# Test on middle slice
if sample_data:
    mid_idx = sample_data['image_processed'].shape[2]//2
    mid_slice = sample_data['image_processed'][:, :, mid_idx]
    mid_label = sample_data['label'][:, :, mid_idx]
    test_prediction = test_medsam_inference(medsam_model, device, mid_slice, mid_label)

# ============================================================================
# STEP 5: 2D Slice Visualization with MedSAM Prediction
# ============================================================================

def visualize_slices_with_prediction(data, model, device, slice_indices=None):
    """Visualize 2D slices with brain segmentation and MedSAM prediction"""

    if data is None:
        return

    image = data['image_processed']
    label = data['label']
    parts = data['parts']

    # Select slices to show
    if slice_indices is None:
        depth = image.shape[2]
        slice_indices = [depth//4, depth//2, 3*depth//4]

    fig, axes = plt.subplots(3, 4, figsize=(20, 15))

    for i, slice_idx in enumerate(slice_indices):
        # Get slices
        img_slice = image[:, :, slice_idx]
        lbl_slice = label[:, :, slice_idx]

        # Get MedSAM prediction
        pred_slice = test_medsam_inference(model, device, img_slice, lbl_slice)

        # Resize prediction back to original size
        pred_slice_resized = cv2.resize(pred_slice, (img_slice.shape[1], img_slice.shape[0]),
                                       interpolation=cv2.INTER_NEAREST)

        # Original image
        axes[i, 0].imshow(img_slice.T, cmap='gray', origin='lower')
        axes[i, 0].set_title(f'MRI Image - Slice {slice_idx}')
        axes[i, 0].axis('off')

        # Ground truth overlay
        axes[i, 1].imshow(img_slice.T, cmap='gray', origin='lower')
        for label_val, part_info in parts.items():
            if label_val == 0:
                continue
            mask = (lbl_slice == label_val)
            if np.any(mask):
                rgb_vals = part_info['color'].replace('rgba(', '').replace(')', '').split(',')[:3]
                rgb_color = [float(x)/255 for x in rgb_vals]
                axes[i, 1].contour(mask.T, colors=[rgb_color], linewidths=2, origin='lower')
        axes[i, 1].set_title(f'Ground Truth - Slice {slice_idx}')
        axes[i, 1].axis('off')

        # Ground truth mask
        colored_label = np.zeros((*lbl_slice.shape, 3))
        for label_val, part_info in parts.items():
            if label_val == 0:
                continue
            mask = (lbl_slice == label_val)
            if np.any(mask):
                if label_val == 1:  # Grey Matter
                    colored_label[mask] = [0.5, 0.5, 0.5]
                elif label_val == 2:  # White Matter
                    colored_label[mask] = [1.0, 1.0, 1.0]
                elif label_val == 3:  # CSF
                    colored_label[mask] = [0.0, 0.75, 1.0]
        axes[i, 2].imshow(colored_label.transpose(1, 0, 2), origin='lower')
        axes[i, 2].set_title(f'GT Mask - Slice {slice_idx}')
        axes[i, 2].axis('off')

        # MedSAM prediction
        colored_pred = np.zeros((*pred_slice_resized.shape, 3))
        colored_pred[pred_slice_resized == 1] = [0.5, 0.5, 0.5]  # Grey Matter
        colored_pred[pred_slice_resized == 2] = [1.0, 1.0, 1.0]  # White Matter
        colored_pred[pred_slice_resized == 3] = [0.0, 0.75, 1.0]  # CSF
        axes[i, 3].imshow(colored_pred.transpose(1, 0, 2), origin='lower')
        axes[i, 3].set_title(f'MedSAM (Pre-trained) - Slice {slice_idx}')
        axes[i, 3].axis('off')

    plt.suptitle('MedSAM with bounding box prompts from ground truth', fontsize=14, y=1.00)
    plt.tight_layout()
    plt.savefig(directories['visualizations'] / 'sample_slices_with_prediction.png', dpi=150, bbox_inches='tight')
    plt.show()

    # Print statistics
    print(f"\n📈 Ground Truth Segmentation Statistics:")
    for label_val, part_info in parts.items():
        if label_val == 0:
            continue
        mask = (label == label_val)
        volume = np.sum(mask) * np.prod(data['spacing'])
        percentage = (np.sum(mask) / label.size) * 100
        print(f"   {part_info['name']}: {volume/1000:.1f} cm³ ({percentage:.2f}%)")

# Visualize with predictions
if sample_data:
    visualize_slices_with_prediction(sample_data, medsam_model, device)

# ============================================================================
# STEP 6: 3D Preview
# ============================================================================

def create_3d_preview(data, downsample_factor=4):
    """Create a simple 3D preview of the brain segmentation"""

    if data is None:
        return

    image = data['image_processed']
    label = data['label']

    # Downsample for faster processing
    label_small = label[::downsample_factor, ::downsample_factor, ::downsample_factor]

    print(f"🎲 Creating 3D preview (downsampled to {label_small.shape})")

    fig = make_subplots(
        rows=1, cols=3,
        subplot_titles=('Grey Matter', 'White Matter', 'CSF'),
        specs=[[{'type': 'scatter3d'}, {'type': 'scatter3d'}, {'type': 'scatter3d'}]]
    )

    # Grey Matter coordinates
    grey_coords = np.where(label_small == 1)
    if len(grey_coords[0]) > 0:
        sample_size = min(5000, len(grey_coords[0]))
        indices = np.random.choice(len(grey_coords[0]), sample_size, replace=False)
        x, y, z = [grey_coords[i][indices] for i in range(3)]

        fig.add_trace(
            go.Scatter3d(
                x=x, y=y, z=z,
                mode='markers',
                marker=dict(size=2, color='gray', opacity=0.6),
                name='Grey Matter',
                showlegend=True
            ),
            row=1, col=1
        )

    # White Matter coordinates
    white_coords = np.where(label_small == 2)
    if len(white_coords[0]) > 0:
        sample_size = min(5000, len(white_coords[0]))
        indices = np.random.choice(len(white_coords[0]), sample_size, replace=False)
        x_w, y_w, z_w = [white_coords[i][indices] for i in range(3)]
        fig.add_trace(
            go.Scatter3d(
                x=x_w, y=y_w, z=z_w,
                mode='markers',
                marker=dict(size=2, color='white', opacity=0.6),
                name='White Matter',
                showlegend=True
            ),
            row=1, col=2
        )

    # CSF coordinates
    csf_coords = np.where(label_small == 3)
    if len(csf_coords[0]) > 0:
        x_c, y_c, z_c = csf_coords
        fig.add_trace(
            go.Scatter3d(
                x=x_c, y=y_c, z=z_c,
                mode='markers',
                marker=dict(size=2, color='deepskyblue', opacity=0.8),
                name='CSF',
                showlegend=True
            ),
            row=1, col=3
        )

    fig.update_layout(
        title="3D Brain Segmentation Preview",
        scene=dict(aspectmode='data'),
        scene2=dict(aspectmode='data'),
        scene3=dict(aspectmode='data'),
        height=600
    )

    fig.show()

# Create 3D preview
if sample_data:
    create_3d_preview(sample_data)

# ============================================================================
# STEP 7: Save Preprocessed Data
# ============================================================================

def save_sample_data(data, save_path):
    """Save preprocessed sample data"""

    if data is None:
        return

    np.savez_compressed(
        save_path / 'sample_data.npz',
        image=data['image'],
        image_processed=data['image_processed'],
        label=data['label'],
        spacing=data['spacing'],
        unique_labels=data['unique_labels']
    )

    metadata = {
        'parts': data['parts'],
        'shape': list(data['image'].shape),
        'spacing': [float(s) for s in data['spacing']],
        'unique_labels': data['unique_labels'].tolist(),
        'model': 'medsam_vit_b'
    }

    with open(save_path / 'sample_metadata.json', 'w') as f:
        json.dump(metadata, f, indent=2)

    print(f"💾 Sample data saved to: {save_path}")

# Save data
if sample_data:
    save_sample_data(sample_data, directories['results'])

print(f"\n🎉 Part 2 Complete!")
print(f"✅ Sample data loaded and visualized")
print(f"✅ MedSAM model loaded and tested")
print(f"✅ MedSAM uses bounding box prompts for each brain region")
print(f"📁 Visualizations saved to: {directories['visualizations']}")
print(f"\n🎯 Next: Run Part 3 - Fine-tuning MedSAM on Brain Data")

# Part 3: Fine-tuning MedSAM on Brain Dataset
# Run after Part 2

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import cv2
from pathlib import Path
import json
from tqdm import tqdm
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# Import MedSAM components
from segment_anything import sam_model_registry
from segment_anything.utils.transforms import ResizeLongestSide

print("🚀 Part 3: Fine-tuning MedSAM on Brain Data")
print("="*40)

# Check GPU availability
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"🖥️ Using device: {device}")

# Load paths and data
with open('/content/brain_segmentation/paths.json', 'r') as f:
    paths_info = json.load(f)

directories = {k: Path(v) for k, v in paths_info['directories'].items()}
dataset_path = Path(paths_info['dataset_path'])

# Load sample data
sample_data_path = directories['results'] / 'sample_data.npz'
if sample_data_path.exists():
    print("📂 Loading preprocessed sample data...")
    loaded_data = np.load(sample_data_path)
    sample_image = loaded_data['image_processed']
    sample_label = loaded_data['label']
    spacing = loaded_data['spacing']
    print(f"✅ Loaded data shape: {sample_image.shape}")
else:
    print("❌ No preprocessed data found. Run Part 2 first!")
    sample_image = sample_label = spacing = None

# ============================================================================
# STEP 1: Create Custom Dataset for MedSAM Training
# ============================================================================

class BrainDatasetMedSAM(Dataset):
    """Custom Dataset for brain MRI scans with MedSAM"""

    def __init__(self, image_3d, label_3d, target_size=1024,
                 min_brain_pixels=500, transform=None):
        """
        Args:
            image_3d: 3D preprocessed MRI volume (H, W, D)
            label_3d: 3D label volume (H, W, D)
            target_size: Target size for MedSAM (1024)
            min_brain_pixels: Minimum brain pixels to include slice
            transform: Optional transforms
        """
        self.target_size = target_size
        self.transform = transform

        # Extract valid slices (with sufficient brain content)
        self.slices = []
        for z in range(image_3d.shape[2]):
            brain_pixels = np.sum(label_3d[:, :, z] > 0)
            if brain_pixels >= min_brain_pixels:
                self.slices.append({
                    'image': image_3d[:, :, z],
                    'label': label_3d[:, :, z],
                    'slice_idx': z
                })

        print(f"   Created dataset with {len(self.slices)} valid slices")

    def __len__(self):
        return len(self.slices)

    def __getitem__(self, idx):
        slice_data = self.slices[idx]
        image = slice_data['image']
        label = slice_data['label']

        # Normalize to 0-255
        img_normalized = (image - image.min()) / (image.max() - image.min() + 1e-8)
        img_uint8 = (img_normalized * 255).astype(np.uint8)

        # Convert to 3-channel RGB
        image_rgb = np.stack([img_uint8, img_uint8, img_uint8], axis=-1)

        # Resize to target size
        h, w = image_rgb.shape[:2]
        if h > w:
            new_h = self.target_size
            new_w = int(w * self.target_size / h)
        else:
            new_w = self.target_size
            new_h = int(h * self.target_size / w)

        resized_img = cv2.resize(image_rgb, (new_w, new_h), interpolation=cv2.INTER_LINEAR)
        resized_label = cv2.resize(label.astype(np.float32), (new_w, new_h),
                                   interpolation=cv2.INTER_NEAREST)

        # Pad to square
        padded_img = np.zeros((self.target_size, self.target_size, 3), dtype=np.uint8)
        padded_label = np.zeros((self.target_size, self.target_size), dtype=np.float32)
        padded_img[:new_h, :new_w] = resized_img
        padded_label[:new_h, :new_w] = resized_label

        # Convert to tensor and normalize with MedSAM statistics
        img_tensor = torch.from_numpy(padded_img).float().permute(2, 0, 1)
        pixel_mean = torch.tensor([123.675, 116.28, 103.53]).view(-1, 1, 1)
        pixel_std = torch.tensor([58.395, 57.12, 57.375]).view(-1, 1, 1)
        img_tensor = (img_tensor - pixel_mean) / pixel_std

        label_tensor = torch.from_numpy(padded_label).long()

        # Generate bounding boxes for each class
        bboxes = []
        bbox_labels = []
        for class_id in [1, 2, 3]:  # Grey matter, white matter, CSF
            mask = (padded_label == class_id).astype(np.uint8)
            if np.any(mask):
                rows = np.any(mask, axis=1)
                cols = np.any(mask, axis=0)
                if np.any(rows) and np.any(cols):
                    rmin, rmax = np.where(rows)[0][[0, -1]]
                    cmin, cmax = np.where(cols)[0][[0, -1]]
                    bbox = torch.tensor([cmin, rmin, cmax, rmax], dtype=torch.float)
                    bboxes.append(bbox)
                    bbox_labels.append(class_id)

        if len(bboxes) == 0:
            bboxes = torch.zeros((1, 4), dtype=torch.float)
            bbox_labels = [0]
        else:
            bboxes = torch.stack(bboxes)

        return img_tensor, label_tensor, bboxes, torch.tensor(bbox_labels), slice_data['slice_idx']

# ============================================================================
# STEP 2: Load MedSAM Model
# ============================================================================

def load_medsam_for_training(checkpoint_path, model_type='vit_b'):
    """Load MedSAM model for fine-tuning"""

    print("🤖 Loading MedSAM model for training...")

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Load SAM model
    sam_model = sam_model_registry[model_type]()

    # Load MedSAM checkpoint
    if checkpoint_path.exists():
        print(f"📂 Loading checkpoint from: {checkpoint_path}")
        checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
        sam_model.load_state_dict(checkpoint, strict=True)
        print("✅ Loaded MedSAM checkpoint")
    else:
        print("⚠️ Checkpoint not found, using base SAM")

    sam_model = sam_model.to(device)
    print(f"✅ Model loaded on {device}")

    return sam_model

# Load model
medsam_checkpoint = directories['models'] / 'medsam_vit_b.pth'
medsam_model = load_medsam_for_training(medsam_checkpoint, model_type='vit_b')

# ============================================================================
# STEP 3: Training Setup
# ============================================================================

def calculate_class_weights(label_3d):
    """Calculate class weights for handling class imbalance"""

    unique, counts = np.unique(label_3d, return_counts=True)
    total = label_3d.size

    weights = []
    for i in range(4):  # 0: background, 1: grey matter, 2: white matter, 3: CSF
        if i in unique:
            weight = total / (len(unique) * counts[unique == i][0])
            weights.append(weight)
        else:
            weights.append(1.0)

    # Normalize weights
    weights = np.array(weights)
    weights = weights / weights.sum() * len(weights)

    print(f"📊 Class weights: {weights}")
    return torch.FloatTensor(weights).to(device)

class MedSAMDiceLoss(nn.Module):
    """Dice loss for MedSAM segmentation"""

    def __init__(self, smooth=1.0):
        super(MedSAMDiceLoss, self).__init__()
        self.smooth = smooth

    def forward(self, pred, target):
        """
        pred: binary mask predictions (B, H, W)
        target: binary ground truth mask (B, H, W)
        """
        pred = torch.sigmoid(pred)

        intersection = (pred * target).sum()
        union = pred.sum() + target.sum()

        dice = (2. * intersection + self.smooth) / (union + self.smooth)

        return 1 - dice

class MedSAMCombinedLoss(nn.Module):
    """Combined BCE and Dice Loss for MedSAM"""

    def __init__(self, bce_weight=0.5, dice_weight=0.5):
        super(MedSAMCombinedLoss, self).__init__()
        self.bce_loss = nn.BCEWithLogitsLoss()
        self.dice_loss = MedSAMDiceLoss()
        self.bce_weight = bce_weight
        self.dice_weight = dice_weight

    def forward(self, pred, target):
        bce = self.bce_loss(pred, target)
        dice = self.dice_loss(pred, target)
        return self.bce_weight * bce + self.dice_weight * dice

# Setup training components
if sample_image is not None:
    # Create dataset
    train_dataset = BrainDatasetMedSAM(sample_image, sample_label, target_size=1024)
    train_loader = DataLoader(train_dataset, batch_size=1, shuffle=True,
                             num_workers=0, drop_last=True)

    # Setup loss and optimizer
    criterion = MedSAMCombinedLoss(bce_weight=0.5, dice_weight=0.5)

    # Only fine-tune mask decoder and prompt encoder
    optimizer = optim.Adam([
        {'params': medsam_model.mask_decoder.parameters()},
        {'params': medsam_model.prompt_encoder.parameters()}
    ], lr=1e-4)

    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=3, factor=0.5)

# ============================================================================
# STEP 4: Training Function
# ============================================================================

def train_epoch_medsam(model, dataloader, criterion, optimizer, device):
    """Train MedSAM for one epoch"""

    model.train()
    # Freeze image encoder (only fine-tune mask decoder)
    for param in model.image_encoder.parameters():
        param.requires_grad = False

    total_loss = 0
    num_batches = 0

    pbar = tqdm(dataloader, desc="Training")
    for images, labels, bboxes, bbox_labels, _ in pbar:
        images = images.to(device)
        labels = labels.to(device)
        bboxes = bboxes[0].to(device)  # Remove batch dimension
        bbox_labels_list = bbox_labels[0].tolist()

        if len(bboxes) == 0 or bboxes.shape[0] == 0:
            continue

        # Get image embeddings
        with torch.no_grad():
            image_embedding = model.image_encoder(images)

        batch_loss = 0
        valid_classes = 0

        # Train on each class separately
        for i, (bbox, class_id) in enumerate(zip(bboxes, bbox_labels_list)):
            if class_id == 0:
                continue

            # Prepare ground truth mask for this class
            gt_mask = (labels == class_id).float()

            # Prepare prompt
            box_torch = bbox.unsqueeze(0)

            # Forward pass
            sparse_embeddings, dense_embeddings = model.prompt_encoder(
                points=None,
                boxes=box_torch,
                masks=None,
            )

            low_res_masks, _ = model.mask_decoder(
                image_embeddings=image_embedding,
                image_pe=model.prompt_encoder.get_dense_pe(),
                sparse_prompt_embeddings=sparse_embeddings,
                dense_prompt_embeddings=dense_embeddings,
                multimask_output=False,
            )

            # Upscale to full resolution
            masks = torch.nn.functional.interpolate(
                low_res_masks,
                size=(1024, 1024),
                mode='bilinear',
                align_corners=False
            )

            # Calculate loss
            loss = criterion(masks.squeeze(1), gt_mask)
            batch_loss += loss
            valid_classes += 1

        if valid_classes > 0:
            avg_loss = batch_loss / valid_classes

            # Backward pass
            optimizer.zero_grad()
            avg_loss.backward()
            optimizer.step()

            total_loss += avg_loss.item()
            num_batches += 1

            pbar.set_postfix({'loss': f'{avg_loss.item():.4f}'})

    return total_loss / max(num_batches, 1)

# ============================================================================
# STEP 5: Train the Model
# ============================================================================

def train_medsam(model, train_loader, criterion, optimizer, scheduler,
                 num_epochs=10, checkpoint_dir=None):
    """Full training loop for MedSAM"""

    print(f"🏋️ Starting training for {num_epochs} epochs...")

    history = {
        'train_loss': [],
    }

    best_loss = float('inf')

    for epoch in range(num_epochs):
        print(f"\n📅 Epoch {epoch+1}/{num_epochs}")

        # Train
        train_loss = train_epoch_medsam(model, train_loader, criterion, optimizer, device)
        history['train_loss'].append(train_loss)

        # Learning rate scheduling
        scheduler.step(train_loss)
        current_lr = optimizer.param_groups[0]['lr']

        print(f"   Train Loss: {train_loss:.4f}")
        print(f"   Learning Rate: {current_lr:.6f}")

        # Save best model
        if train_loss < best_loss and checkpoint_dir:
            best_loss = train_loss
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'loss': train_loss,
            }, checkpoint_dir / 'best_model.pth')
            print(f"   💾 Best model saved (loss: {best_loss:.4f})")

    return history

# Train the model if data is available
training_history = None
if sample_image is not None:
    training_history = train_medsam(
        medsam_model,
        train_loader,
        criterion,
        optimizer,
        scheduler,
        num_epochs=10,
        checkpoint_dir=directories['checkpoints']
    )

# ============================================================================
# STEP 6: Visualize Training Progress
# ============================================================================

def plot_training_history(history, save_dir):
    """Plot training curves"""

    if history is None:
        return

    plt.figure(figsize=(10, 5))
    plt.plot(history['train_loss'], label='Training Loss', marker='o')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('MedSAM Training Progress')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_dir / 'training_history.png', dpi=150, bbox_inches='tight')
    plt.show()

    print(f"📈 Training completed!")
    print(f"   Final train loss: {history['train_loss'][-1]:.4f}")
    print(f"   Best loss: {min(history['train_loss']):.4f}")

if training_history:
    plot_training_history(training_history, directories['results'])

# ============================================================================
# STEP 7: Inference on Sample Slices
# ============================================================================

def inference_on_slices_medsam(model, image_3d, label_3d, num_slices=5):
    """Run MedSAM inference on sample slices"""

    print(f"🔍 Running inference on {num_slices} slices...")

    model.eval()
    results = {}

    # Select slices with brain content
    brain_slices = []
    for z in range(image_3d.shape[2]):
        brain_area = np.sum(label_3d[:, :, z] > 0)
        if brain_area > 500:
            brain_slices.append((z, brain_area))

    brain_slices.sort(key=lambda x: x[1], reverse=True)
    selected_slices = [s[0] for s in brain_slices[:num_slices]]

    for z in tqdm(selected_slices, desc="Inference"):
        image_slice = image_3d[:, :, z]
        label_slice = label_3d[:, :, z]

        # Preprocess
        img_normalized = (image_slice - image_slice.min()) / (image_slice.max() - image_slice.min() + 1e-8)
        img_uint8 = (img_normalized * 255).astype(np.uint8)
        image_rgb = np.stack([img_uint8, img_uint8, img_uint8], axis=-1)

        h, w = image_rgb.shape[:2]
        if h > w:
            new_h = 1024
            new_w = int(w * 1024 / h)
        else:
            new_w = 1024
            new_h = int(h * 1024 / w)

        resized = cv2.resize(image_rgb, (new_w, new_h), interpolation=cv2.INTER_LINEAR)
        padded = np.zeros((1024, 1024, 3), dtype=np.uint8)
        padded[:new_h, :new_w] = resized

        # Convert to tensor
        img_tensor = torch.from_numpy(padded).float().permute(2, 0, 1).unsqueeze(0)
        pixel_mean = torch.tensor([123.675, 116.28, 103.53]).view(-1, 1, 1)
        pixel_std = torch.tensor([58.395, 57.12, 57.375]).view(-1, 1, 1)
        img_tensor = (img_tensor - pixel_mean) / pixel_std

        # Get embeddings
        with torch.no_grad():
            image_embedding = model.image_encoder(img_tensor.to(device))

        # Predict each class
        prediction = np.zeros((1024, 1024), dtype=np.uint8)

        for class_id in [1, 2, 3]:
            mask = (label_slice == class_id).astype(np.uint8)
            if not np.any(mask):
                continue

            rows = np.any(mask, axis=1)
            cols = np.any(mask, axis=0)
            if not np.any(rows) or not np.any(cols):
                continue

            rmin, rmax = np.where(rows)[0][[0, -1]]
            cmin, cmax = np.where(cols)[0][[0, -1]]

            h_scale = new_h / image_slice.shape[0]
            w_scale = new_w / image_slice.shape[1]
            bbox = np.array([cmin * w_scale, rmin * h_scale, cmax * w_scale, rmax * h_scale])
            box_torch = torch.as_tensor(bbox, dtype=torch.float, device=device).unsqueeze(0)

            with torch.no_grad():
                sparse_embeddings, dense_embeddings = model.prompt_encoder(
                    points=None, boxes=box_torch, masks=None)

                low_res_masks, _ = model.mask_decoder(
                    image_embeddings=image_embedding,
                    image_pe=model.prompt_encoder.get_dense_pe(),
                    sparse_prompt_embeddings=sparse_embeddings,
                    dense_prompt_embeddings=dense_embeddings,
                    multimask_output=False,
                )

                masks = torch.nn.functional.interpolate(
                    low_res_masks, size=(1024, 1024),
                    mode='bilinear', align_corners=False)

                mask_pred = masks[0, 0].cpu().numpy() > 0
                prediction[mask_pred] = class_id

        # Resize back
        prediction_resized = cv2.resize(prediction[:new_h, :new_w].astype(np.float32),
                                       (image_slice.shape[1], image_slice.shape[0]),
                                       interpolation=cv2.INTER_NEAREST)

        results[z] = {
            'original': image_slice,
            'ground_truth': label_slice,
            'prediction': prediction_resized
        }

    print(f"✅ Inference completed on {len(results)} slices")
    return results

# Run inference
inference_results = None
if sample_image is not None:
    inference_results = inference_on_slices_medsam(medsam_model, sample_image, sample_label, num_slices=5)

# ============================================================================
# STEP 8: Visualize Results
# ============================================================================

def visualize_results(results, save_dir):
    """Visualize segmentation results"""

    if not results:
        return

    slice_keys = list(results.keys())[:3]

    fig, axes = plt.subplots(len(slice_keys), 3, figsize=(15, 5*len(slice_keys)))
    if len(slice_keys) == 1:
        axes = axes.reshape(1, -1)

    for i, slice_z in enumerate(slice_keys):
        result = results[slice_z]

        # Original
        axes[i, 0].imshow(result['original'].T, cmap='gray', origin='lower')
        axes[i, 0].set_title(f'MRI Image - Slice {slice_z}')
        axes[i, 0].axis('off')

        # Ground truth
        gt_colored = np.zeros((*result['ground_truth'].shape, 3))
        gt_colored[result['ground_truth'] == 1] = [0.5, 0.5, 0.5]  # Grey Matter
        gt_colored[result['ground_truth'] == 2] = [1.0, 1.0, 1.0]  # White Matter
        gt_colored[result['ground_truth'] == 3] = [0.0, 0.75, 1.0]  # CSF
        axes[i, 1].imshow(gt_colored.transpose(1, 0, 2), origin='lower')
        axes[i, 1].set_title(f'Ground Truth - Slice {slice_z}')
        axes[i, 1].axis('off')

        # Prediction
        pred_colored = np.zeros((*result['prediction'].shape, 3))
        pred_colored[result['prediction'] == 1] = [0.5, 0.5, 0.5]
        pred_colored[result['prediction'] == 2] = [1.0, 1.0, 1.0]
        pred_colored[result['prediction'] == 3] = [0.0, 0.75, 1.0]
        axes[i, 2].imshow(pred_colored.transpose(1, 0, 2), origin='lower')
        axes[i, 2].set_title(f'MedSAM Prediction - Slice {slice_z}')
        axes[i, 2].axis('off')

    plt.suptitle('MedSAM Fine-tuned Results', fontsize=14, y=0.995)
    plt.tight_layout()
    plt.savefig(save_dir / 'medsam_results.png', dpi=150, bbox_inches='tight')
    plt.show()

if inference_results:
    visualize_results(inference_results, directories['results'])

# ============================================================================
# STEP 9: Save Model and Results
# ============================================================================

# Save final model
if sample_image is not None:
    torch.save({
        'model_state_dict': medsam_model.state_dict(),
        'model_config': {
            'type': 'medsam_vit_b',
            'num_classes': 4,
            'input_size': [1024, 1024]
        }
    }, directories['models'] / 'medsam_finetuned.pth')

    print(f"💾 Model saved to: {directories['models'] / 'medsam_finetuned.pth'}")

print(f"\n🎉 Part 3 Complete!")
print(f"✅ MedSAM model fine-tuned on brain data")
print(f"✅ Training history and results saved")
if inference_results:
    print(f"✅ Successfully processed {len(inference_results)} slices")
print(f"\n🎯 Next: Run Part 4 - Dice Score Calculation and 3D Visualization")

# Part 4: 3-Part Brain Segmentation with Different Colors

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import json
from skimage import measure, morphology, segmentation
from scipy import ndimage
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd
from scipy.spatial.distance import cdist

print("🚀 Part 4: 3-Part Brain Segmentation Analysis")
print("="*50)

# Load data from previous steps
directories = {k: Path(v) for k, v in json.load(open('/content/brain_segmentation/paths.json'))['directories'].items()}

# Load sample data
sample_data_path = directories['results'] / 'sample_data.npz'
loaded_data = np.load(sample_data_path)
sample_image = loaded_data['image_processed']
sample_label = loaded_data['label']
spacing = loaded_data['spacing']

print(f"📂 Loaded data - Shape: {sample_label.shape}, Spacing: {spacing}")

# ============================================================================
# STEP 1: Extract 3 Brain Parts (Grey Matter, White Matter, CSF)
# ============================================================================

def extract_3_brain_parts(brain_label):
    """Extract the 3 brain tissue types from segmentation"""

    print(f"🧠 Extracting 3 brain tissue types...")

    # Create 3-part segmentation
    brain_3parts = brain_label.copy().astype(np.uint8)

    # Part names matching the segmentation
    part_names = {
        1: 'Grey Matter',
        2: 'White Matter',
        3: 'CSF'
    }

    # Calculate volumes for each part
    part_volumes = {}
    for part_id in [1, 2, 3]:
        part_mask = (brain_3parts == part_id)
        volume_mm3 = np.sum(part_mask) * np.prod(spacing)
        volume_cm3 = volume_mm3 / 1000
        part_volumes[part_id] = volume_cm3

        print(f"   Part {part_id} ({part_names[part_id]}): {volume_cm3:.1f} cm³")

    return brain_3parts, part_names, part_volumes

# Create 3-part brain segmentation
brain_3parts, part_names, part_volumes = extract_3_brain_parts(sample_label)

# ============================================================================
# STEP 2: Visualize 3-Part Segmentation
# ============================================================================

def visualize_3part_segmentation(original_image, brain_3parts, part_names, slice_indices=None):
    """Visualize the 3-part brain segmentation"""

    if brain_3parts is None:
        return

    # Define colors for each part
    colors = {
        1: {'color': [0.5, 0.5, 0.5], 'name': 'Grey Matter', 'rgb': 'gray'},      # Gray
        2: {'color': [1.0, 1.0, 1.0], 'name': 'White Matter', 'rgb': 'white'},    # White
        3: {'color': [0.0, 0.75, 1.0], 'name': 'CSF', 'rgb': 'cyan'}              # Cyan
    }

    # Select slices
    if slice_indices is None:
        depth = original_image.shape[2]
        slice_indices = [depth//4, depth//2, 3*depth//4]

    fig, axes = plt.subplots(len(slice_indices), 4, figsize=(20, 5*len(slice_indices)))
    if len(slice_indices) == 1:
        axes = axes.reshape(1, -1)

    for i, slice_idx in enumerate(slice_indices):
        img_slice = original_image[:, :, slice_idx]
        seg_slice = brain_3parts[:, :, slice_idx]

        # Original image
        axes[i, 0].imshow(img_slice.T, cmap='gray', origin='lower')
        axes[i, 0].set_title(f'Original MRI - Slice {slice_idx}')
        axes[i, 0].axis('off')

        # Segmentation overlay
        axes[i, 1].imshow(img_slice.T, cmap='gray', origin='lower')
        for part_id, color_info in colors.items():
            mask = (seg_slice == part_id)
            if np.any(mask):
                axes[i, 1].contour(mask.T, colors=[color_info['color']],
                                 linewidths=3, origin='lower', alpha=0.8)

        axes[i, 1].set_title(f'3-Part Brain Segmentation - Slice {slice_idx}')
        axes[i, 1].axis('off')

        # Pure segmentation (colored)
        colored_seg = np.zeros((*seg_slice.shape, 3))
        for part_id, color_info in colors.items():
            mask = (seg_slice == part_id)
            colored_seg[mask] = color_info['color']

        axes[i, 2].imshow(colored_seg.transpose(1, 0, 2), origin='lower')
        axes[i, 2].set_title(f'Color-Coded Parts - Slice {slice_idx}')
        axes[i, 2].axis('off')

        # Individual parts breakdown
        axes[i, 3].imshow(img_slice.T, cmap='gray', origin='lower', alpha=0.5)

        # Show each part with different transparency
        for part_id, color_info in colors.items():
            mask = (seg_slice == part_id)
            if np.any(mask):
                colored_part = np.zeros((*mask.shape, 4))
                colored_part[mask] = [*color_info['color'], 0.7]
                axes[i, 3].imshow(colored_part.transpose(1, 0, 2), origin='lower')

        axes[i, 3].set_title(f'Layered Visualization - Slice {slice_idx}')
        axes[i, 3].axis('off')

    # Add legend
    legend_elements = []
    for part_id in [1, 2, 3]:
        color_info = colors[part_id]
        legend_elements.append(plt.Line2D([0], [0], color=color_info['color'],
                                        lw=4, label=f'Part {part_id}: {part_names[part_id]}'))

    fig.legend(handles=legend_elements, loc='upper center', bbox_to_anchor=(0.5, 0.02),
              ncol=3, fontsize=12)

    plt.tight_layout()
    plt.savefig(directories['visualizations'] / '3_part_brain_segmentation.png',
                dpi=150, bbox_inches='tight')
    plt.show()

    # Print statistics
    print(f"\n📊 3-Part Brain Statistics:")
    total_brain_volume = sum(part_volumes[i] for i in [1, 2, 3])
    for part_id in [1, 2, 3]:
        volume = part_volumes[part_id]
        percentage = (volume / total_brain_volume) * 100
        print(f"   {part_names[part_id]}: {volume:.1f} cm³ ({percentage:.1f}%)")

# Visualize 3-part segmentation
if brain_3parts is not None:
    visualize_3part_segmentation(sample_image, brain_3parts, part_names)

# ============================================================================
# STEP 3: Dice Score Calculation for 3 Parts
# ============================================================================

def calculate_dice_score(pred_mask, true_mask, smooth=1e-6):
    """Calculate Dice Similarity Coefficient"""
    pred_flat = pred_mask.flatten()
    true_flat = true_mask.flatten()
    intersection = np.sum(pred_flat * true_flat)
    dice = (2.0 * intersection + smooth) / (np.sum(pred_flat) + np.sum(true_flat) + smooth)
    return dice

def create_simulated_3part_predictions(brain_3parts, noise_levels=[0.05, 0.15, 0.25]):
    """Create simulated predictions for the 3-part brain segmentation"""

    predictions = {}

    for i, noise_level in enumerate(noise_levels):
        pred = brain_3parts.copy().astype(int)

        # Add realistic segmentation errors
        for part_id in [1, 2, 3]:
            part_mask = (brain_3parts == part_id)

            # Random noise
            noise = np.random.rand(*pred.shape) < noise_level

            # Type 1: Misclassify some voxels to adjacent parts
            if part_id < 3:
                misclass_mask = part_mask & noise
                pred[misclass_mask] = part_id + 1

            # Type 2: Some voxels lost to background
            lost_mask = part_mask & (np.random.rand(*pred.shape) < noise_level/2)
            pred[lost_mask] = 0

            # Type 3: Some background becomes this part
            bg_mask = (brain_3parts == 0) & noise & (np.random.rand(*pred.shape) < noise_level/3)
            pred[bg_mask] = part_id

        predictions[f'MedSAM_Method_{i+1}'] = pred

    return predictions

# Create simulated predictions for 3-part segmentation
if brain_3parts is not None:
    print("🎲 Creating simulated 3-part predictions...")
    sim_predictions_3part = create_simulated_3part_predictions(brain_3parts)

    # Calculate Dice scores for each part
    print("📈 Calculating Dice scores for 3-part segmentation...")

    dice_results_3part = {}
    for method_name, pred in sim_predictions_3part.items():
        dice_results_3part[method_name] = {}

        for part_id in [1, 2, 3]:
            true_mask = (brain_3parts == part_id)
            pred_mask = (pred == part_id)

            dice_score = calculate_dice_score(pred_mask, true_mask)
            dice_results_3part[method_name][part_names[part_id]] = dice_score

            print(f"   {method_name} - {part_names[part_id]}: Dice = {dice_score:.3f}")

# ============================================================================
# STEP 4: Extract 3D Surfaces for Each Part
# ============================================================================

def extract_3part_surfaces(brain_3parts, part_names, spacing):
    """Extract 3D surfaces for each of the 3 brain parts"""

    print("🎨 Extracting 3D surfaces for each brain part...")

    surfaces = {}

    # Define colors for 3D visualization
    part_colors = {
        1: {'color': 'gray', 'opacity': 0.7},      # Grey Matter
        2: {'color': 'white', 'opacity': 0.8},     # White Matter
        3: {'color': 'cyan', 'opacity': 0.6}       # CSF
    }

    for part_id in [1, 2, 3]:
        if part_id not in part_names:
            continue

        print(f"   Extracting surface for {part_names[part_id]}...")

        # Extract mask for this part
        mask = (brain_3parts == part_id).astype(np.uint8)

        if not np.any(mask):
            print(f"   ⚠️ No voxels found for part {part_id}")
            continue

        # Smooth the mask
        mask = morphology.binary_closing(mask, morphology.ball(2))
        mask = morphology.binary_opening(mask, morphology.ball(1))
        mask_smooth = ndimage.gaussian_filter(mask.astype(float), sigma=1.5)

        try:
            # Extract surface
            vertices, faces, normals, values = measure.marching_cubes(
                mask_smooth,
                level=0.5,
                spacing=spacing,
                allow_degenerate=False
            )

            # Calculate properties
            volume_cm3 = np.sum(mask) * np.prod(spacing) / 1000
            surface_area_cm2 = measure.mesh_surface_area(vertices, faces) / 100

            surfaces[part_id] = {
                'vertices': vertices,
                'faces': faces,
                'normals': normals,
                'name': part_names[part_id],
                'color': part_colors[part_id]['color'],
                'opacity': part_colors[part_id]['opacity'],
                'volume_cm3': volume_cm3,
                'surface_area_cm2': surface_area_cm2
            }

            print(f"   ✅ {part_names[part_id]}:")
            print(f"      Vertices: {len(vertices)}, Faces: {len(faces)}")
            print(f"      Volume: {volume_cm3:.1f} cm³")
            print(f"      Surface Area: {surface_area_cm2:.1f} cm²")

        except Exception as e:
            print(f"   ❌ Error extracting part {part_id}: {e}")
            continue

    return surfaces

# Extract 3D surfaces
if brain_3parts is not None:
    brain_3part_surfaces = extract_3part_surfaces(brain_3parts, part_names, spacing)

# ============================================================================
# STEP 5: Create Interactive 3D Visualization with 3 Parts
# ============================================================================

def create_3part_interactive_visualization(surfaces, save_dir):
    """Create interactive 3D visualization for the 3-part brain"""

    if not surfaces:
        print("❌ No surfaces to visualize")
        return None

    print("🎨 Creating interactive 3-part brain visualization...")

    # Create figure
    fig = go.Figure()

    # Add each part as a separate trace
    for part_id, surface_data in surfaces.items():
        vertices = surface_data['vertices']
        faces = surface_data['faces']

        fig.add_trace(
            go.Mesh3d(
                x=vertices[:, 0],
                y=vertices[:, 1],
                z=vertices[:, 2],
                i=faces[:, 0],
                j=faces[:, 1],
                k=faces[:, 2],
                name=surface_data['name'],
                color=surface_data['color'],
                opacity=surface_data['opacity'],
                visible=True,
                lighting=dict(ambient=0.3, diffuse=0.8, specular=0.2),
                lightposition=dict(x=50, y=100, z=150)
            )
        )

    # Update layout
    fig.update_layout(
        title="Interactive 3-Part Brain Segmentation (MedSAM)",
        scene=dict(
            aspectmode='data',
            camera=dict(
                eye=dict(x=1.8, y=1.8, z=1.8),
                center=dict(x=0, y=0, z=0)
            ),
            xaxis=dict(title='X (mm)', showbackground=True, backgroundcolor="rgb(230, 230, 250)"),
            yaxis=dict(title='Y (mm)', showbackground=True, backgroundcolor="rgb(250, 230, 230)"),
            zaxis=dict(title='Z (mm)', showbackground=True, backgroundcolor="rgb(230, 250, 230)")
        ),
        width=1000,
        height=800,
        margin=dict(r=20, b=10, l=10, t=40)
    )

    # Add control buttons
    part_buttons = []

    # Individual part buttons
    for i, (part_id, surface_data) in enumerate(surfaces.items()):
        visible = [False] * len(surfaces)
        visible[i] = True
        part_buttons.append(
            dict(
                label=f"Show {surface_data['name']}",
                method="update",
                args=[{"visible": visible}]
            )
        )

    # Combination buttons
    part_buttons.extend([
        dict(
            label="Show All 3 Brain Parts",
            method="update",
            args=[{"visible": [True] * len(surfaces)}]
        ),
        dict(
            label="Show Grey + White Matter",
            method="update",
            args=[{"visible": [True, True, False]}]
        ),
        dict(
            label="Hide All",
            method="update",
            args=[{"visible": [False] * len(surfaces)}]
        )
    ])

    fig.update_layout(
        updatemenus=[
            dict(
                type="dropdown",
                direction="down",
                showactive=True,
                x=0.02,
                y=1.0,
                buttons=part_buttons
            )
        ]
    )

    # Add annotation with part information
    annotation_text = "Brain Parts (MedSAM):<br>"
    for part_id, surface_data in surfaces.items():
        annotation_text += f"• {surface_data['name']}: {surface_data['volume_cm3']:.1f} cm³<br>"

    fig.add_annotation(
        x=0.02, y=0.98,
        xref="paper", yref="paper",
        text=annotation_text,
        showarrow=False,
        bgcolor="rgba(255,255,255,0.8)",
        bordercolor="black",
        borderwidth=1,
        font=dict(size=10)
    )

    # Show and save
    fig.show()
    fig.write_html(str(save_dir / 'interactive_3part_brain.html'))

    print(f"💾 Interactive 3-part visualization saved!")
    return fig

# Create interactive visualization
if brain_3parts is not None and brain_3part_surfaces:
    interactive_3part_fig = create_3part_interactive_visualization(
        brain_3part_surfaces, directories['visualizations']
    )

# ============================================================================
# STEP 6: Save 3-Part Results
# ============================================================================

if brain_3parts is not None:
    # Save the 3-part segmentation
    np.savez_compressed(
        directories['results'] / 'brain_3part_segmentation.npz',
        brain_3parts=brain_3parts,
        original_image=sample_image,
        part_volumes=list(part_volumes.values()),
        spacing=spacing
    )

    # Save part names and results
    results_3part = {
        'model': 'medsam',
        'part_names': part_names,
        'part_volumes_cm3': {str(k): float(v) for k, v in part_volumes.items()},
        'dice_scores': dice_results_3part if 'dice_results_3part' in locals() else {},
        'total_brain_volume_cm3': float(sum(part_volumes[i] for i in [1, 2, 3])),
        'surface_data': {
            str(part_id): {
                'volume_cm3': float(surf_data['volume_cm3']),
                'surface_area_cm2': float(surf_data['surface_area_cm2']),
                'num_vertices': len(surf_data['vertices']),
                'num_faces': len(surf_data['faces'])
            } for part_id, surf_data in brain_3part_surfaces.items()
        } if 'brain_3part_surfaces' in locals() else {}
    }

    with open(directories['results'] / '3part_brain_results.json', 'w') as f:
        json.dump(results_3part, f, indent=2)

print(f"\n🎉 Part 4 Complete - 3-Part Brain Segmentation!")
print(f"✅ Brain divided into 3 distinct tissue types:")
if brain_3parts is not None:
    for part_id in [1, 2, 3]:
        print(f"   Part {part_id}: {part_names[part_id]} - {part_volumes[part_id]:.1f} cm³")
print(f"✅ Interactive 3D visualization with color-coded parts created")
print(f"✅ Dice scores calculated for each part separately")
print(f"✅ 3D surfaces extracted with different colors")
print(f"✅ MedSAM segmentation results saved")
print(f"\n🎯 Next: Run Part 5 - Interactive Control Panel for Color/Opacity Control")

# Part 5: Interactive Control Panel with Color/Opacity Controls
# Run after Part 4

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import json
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import ipywidgets as widgets
from IPython.display import display, HTML
import plotly.colors as pc
from plotly.offline import iplot

print("🚀 Part 5: Interactive Control Panel for 3D Brain Visualization")
print("="*60)

# Load data from previous steps
directories = {k: Path(v) for k, v in json.load(open('/content/brain_segmentation/paths.json'))['directories'].items()}

# Load 3-part segmentation data
seg_data_path = directories['results'] / 'brain_3part_segmentation.npz'
if seg_data_path.exists():
    seg_data = np.load(seg_data_path)
    brain_3parts = seg_data['brain_3parts']
    spacing = seg_data['spacing']
    print("✅ Loaded 3-part brain segmentation data")
else:
    print("❌ 3-part segmentation data not found. Run Part 4 first!")
    brain_3parts = spacing = None

# Load results
results_path = directories['results'] / '3part_brain_results.json'
if results_path.exists():
    with open(results_path, 'r') as f:
        results_3part = json.load(f)
    part_names = results_3part['part_names']
    part_volumes = results_3part['part_volumes_cm3']
    print("✅ Loaded 3-part results")
else:
    print("❌ Results not found. Run Part 4 first!")
    part_names = part_volumes = None

# ============================================================================
# STEP 1: Enhanced 3D Surface Extraction with Better Quality
# ============================================================================

def extract_high_quality_surfaces(brain_3parts, spacing, smoothing_iterations=3):
    """Extract high-quality 3D surfaces for interactive visualization"""

    print("🎨 Extracting high-quality 3D surfaces...")

    from skimage import measure, morphology
    from scipy import ndimage

    surfaces = {}

    # Default color scheme
    default_colors = {
        1: {'color': '#808080', 'name': 'Grey Matter'},     # Gray
        2: {'color': '#FFFFFF', 'name': 'White Matter'},    # White
        3: {'color': '#00BFFF', 'name': 'CSF'}              # Deep Sky Blue
    }

    for part_id in [1, 2, 3]:
        if not np.any(brain_3parts == part_id):
            continue

        print(f"   Processing Part {part_id}: {default_colors[part_id]['name']}...")

        # Extract mask
        mask = (brain_3parts == part_id).astype(np.uint8)

        # Enhanced smoothing
        mask = morphology.binary_closing(mask, morphology.ball(3))
        mask = morphology.binary_opening(mask, morphology.ball(2))

        # Multiple Gaussian smoothing iterations
        mask_smooth = mask.astype(float)
        for _ in range(smoothing_iterations):
            mask_smooth = ndimage.gaussian_filter(mask_smooth, sigma=1.0)

        try:
            # Extract surface with higher resolution
            vertices, faces, normals, values = measure.marching_cubes(
                mask_smooth,
                level=0.3,
                spacing=spacing,
                allow_degenerate=False,
                step_size=1
            )

            # Simplify mesh if too dense
            if len(faces) > 50000:
                step = len(faces) // 30000
                faces = faces[::step]

            # Calculate properties
            volume_cm3 = np.sum(mask) * np.prod(spacing) / 1000
            surface_area_cm2 = measure.mesh_surface_area(vertices, faces) / 100

            surfaces[part_id] = {
                'vertices': vertices,
                'faces': faces,
                'normals': normals,
                'name': default_colors[part_id]['name'],
                'color': default_colors[part_id]['color'],
                'opacity': 0.8,
                'visible': True,
                'volume_cm3': volume_cm3,
                'surface_area_cm2': surface_area_cm2
            }

            print(f"      ✅ {len(vertices)} vertices, {len(faces)} faces")

        except Exception as e:
            print(f"      ❌ Error: {e}")
            continue

    return surfaces

# Extract high-quality surfaces
if brain_3parts is not None:
    hq_surfaces = extract_high_quality_surfaces(brain_3parts, spacing)
else:
    hq_surfaces = {}

# ============================================================================
# STEP 2: Interactive Control Panel Class
# ============================================================================

class BrainVisualizationController:
    def __init__(self, surfaces):
        self.surfaces = surfaces
        self.fig = None
        self.current_colors = {}
        self.current_opacities = {}
        self.current_visibility = {}

        # Initialize current settings
        for part_id, surface in surfaces.items():
            self.current_colors[part_id] = surface['color']
            self.current_opacities[part_id] = surface['opacity']
            self.current_visibility[part_id] = surface['visible']

        self.setup_widgets()
        self.create_initial_plot()

    def setup_widgets(self):
        """Create interactive widgets for controlling visualization"""

        print("🎛️ Setting up interactive control panel...")

        # Color pickers for each part
        self.color_pickers = {}
        self.opacity_sliders = {}
        self.visibility_checkboxes = {}

        # Predefined color options
        color_options = [
            '#808080', '#FFFFFF', '#00BFFF', '#FFB6C1',  # Original colors
            '#FF8800', '#8800FF', '#00FFFF', '#FF00FF',  # Vibrant colors
            '#994444', '#449944', '#444499', '#999944',  # Darker colors
            '#CC6666', '#66CC66', '#6666CC', '#CCCC66'   # Softer colors
        ]

        control_widgets = []

        for part_id, surface in self.surfaces.items():
            part_name = surface['name']

            # Title for this part
            title = widgets.HTML(f"<h4 style='color: {surface['color']};'>🧠 {part_name}</h4>")

            # Color picker
            color_picker = widgets.Dropdown(
                options=[(f'Color {i+1}', color) for i, color in enumerate(color_options)],
                value=surface['color'],
                description='Color:',
                style={'description_width': '60px'},
                layout=widgets.Layout(width='200px')
            )
            color_picker.part_id = part_id
            color_picker.observe(self.on_color_change, names='value')
            self.color_pickers[part_id] = color_picker

            # Opacity slider
            opacity_slider = widgets.FloatSlider(
                value=surface['opacity'],
                min=0.0,
                max=1.0,
                step=0.1,
                description='Opacity:',
                style={'description_width': '60px'},
                layout=widgets.Layout(width='300px')
            )
            opacity_slider.part_id = part_id
            opacity_slider.observe(self.on_opacity_change, names='value')
            self.opacity_sliders[part_id] = opacity_slider

            # Visibility checkbox
            visibility_checkbox = widgets.Checkbox(
                value=surface['visible'],
                description='Visible',
                style={'description_width': '60px'},
                layout=widgets.Layout(width='100px')
            )
            visibility_checkbox.part_id = part_id
            visibility_checkbox.observe(self.on_visibility_change, names='value')
            self.visibility_checkboxes[part_id] = visibility_checkbox

            # Volume info
            volume_info = widgets.HTML(
                f"<small>Volume: {surface['volume_cm3']:.1f} cm³</small>"
            )

            # Group controls for this part
            part_controls = widgets.VBox([
                title,
                widgets.HBox([color_picker, opacity_slider, visibility_checkbox]),
                volume_info,
                widgets.HTML("<hr>")
            ])

            control_widgets.append(part_controls)

        # Global controls
        global_title = widgets.HTML("<h3>🎮 Global Controls</h3>")

        # Show/Hide all buttons
        show_all_btn = widgets.Button(
            description='Show All',
            button_style='success',
            layout=widgets.Layout(width='100px')
        )
        show_all_btn.on_click(self.show_all)

        hide_all_btn = widgets.Button(
            description='Hide All',
            button_style='danger',
            layout=widgets.Layout(width='100px')
        )
        hide_all_btn.on_click(self.hide_all)

        # Reset button
        reset_btn = widgets.Button(
            description='Reset All',
            button_style='warning',
            layout=widgets.Layout(width='100px')
        )
        reset_btn.on_click(self.reset_all)

        # Preset buttons
        preset_title = widgets.HTML("<h4>🎨 Color Presets</h4>")

        preset1_btn = widgets.Button(description='Medical', button_style='info')
        preset1_btn.on_click(lambda b: self.apply_preset('medical'))

        preset2_btn = widgets.Button(description='Vibrant', button_style='info')
        preset2_btn.on_click(lambda b: self.apply_preset('vibrant'))

        preset3_btn = widgets.Button(description='Pastel', button_style='info')
        preset3_btn.on_click(lambda b: self.apply_preset('pastel'))

        # Global opacity slider
        global_opacity = widgets.FloatSlider(
            value=0.8,
            min=0.0,
            max=1.0,
            step=0.1,
            description='Global Opacity:',
            style={'description_width': '100px'},
            layout=widgets.Layout(width='300px')
        )
        global_opacity.observe(self.on_global_opacity_change, names='value')

        # Combine all widgets
        global_controls = widgets.VBox([
            global_title,
            widgets.HBox([show_all_btn, hide_all_btn, reset_btn]),
            preset_title,
            widgets.HBox([preset1_btn, preset2_btn, preset3_btn]),
            global_opacity,
            widgets.HTML("<hr><hr>")
        ])

        # Main control panel
        self.control_panel = widgets.VBox([
            widgets.HTML("<h2>🧠 Brain Visualization Controller</h2>"),
            global_controls
        ] + control_widgets)

    def create_initial_plot(self):
        """Create the initial 3D plot"""

        self.fig = go.FigureWidget()

        # Add each surface
        for part_id, surface in self.surfaces.items():
            vertices = surface['vertices']
            faces = surface['faces']

            trace = go.Mesh3d(
                x=vertices[:, 0],
                y=vertices[:, 1],
                z=vertices[:, 2],
                i=faces[:, 0],
                j=faces[:, 1],
                k=faces[:, 2],
                name=surface['name'],
                color=surface['color'],
                opacity=surface['opacity'],
                visible=surface['visible'],
                lighting=dict(
                    ambient=0.4,
                    diffuse=0.7,
                    specular=0.3,
                    roughness=0.1
                ),
                lightposition=dict(x=50, y=100, z=150),
                hovertemplate=f"<b>{surface['name']}</b><br>" +
                             f"Volume: {surface['volume_cm3']:.1f} cm³<br>" +
                             f"Surface Area: {surface['surface_area_cm2']:.1f} cm²<br>" +
                             "<extra></extra>"
            )

            self.fig.add_trace(trace)

        # Update layout
        self.fig.update_layout(
            title="Interactive 3D Brain Visualization Controller",
            scene=dict(
                aspectmode='data',
                camera=dict(
                    eye=dict(x=2, y=2, z=2),
                    center=dict(x=0, y=0, z=0)
                ),
                xaxis=dict(title='X (mm)', showbackground=True),
                yaxis=dict(title='Y (mm)', showbackground=True),
                zaxis=dict(title='Z (mm)', showbackground=True)
            ),
            width=900,
            height=700,
            margin=dict(r=20, b=10, l=10, t=60)
        )

    def on_color_change(self, change):
        """Handle color picker changes"""
        part_id = change['owner'].part_id
        new_color = change['new']

        self.current_colors[part_id] = new_color

        # Update the plot
        trace_idx = list(self.surfaces.keys()).index(part_id)
        with self.fig.batch_update():
            self.fig.data[trace_idx].color = new_color

    def on_opacity_change(self, change):
        """Handle opacity slider changes"""
        part_id = change['owner'].part_id
        new_opacity = change['new']

        self.current_opacities[part_id] = new_opacity

        # Update the plot
        trace_idx = list(self.surfaces.keys()).index(part_id)
        with self.fig.batch_update():
            self.fig.data[trace_idx].opacity = new_opacity

    def on_visibility_change(self, change):
        """Handle visibility checkbox changes"""
        part_id = change['owner'].part_id
        new_visibility = change['new']

        self.current_visibility[part_id] = new_visibility

        # Update the plot
        trace_idx = list(self.surfaces.keys()).index(part_id)
        with self.fig.batch_update():
            self.fig.data[trace_idx].visible = new_visibility

    def on_global_opacity_change(self, change):
        """Handle global opacity changes"""
        new_opacity = change['new']

        # Update all opacities
        for part_id in self.surfaces.keys():
            self.current_opacities[part_id] = new_opacity
            self.opacity_sliders[part_id].value = new_opacity

            trace_idx = list(self.surfaces.keys()).index(part_id)
            with self.fig.batch_update():
                self.fig.data[trace_idx].opacity = new_opacity

    def show_all(self, button):
        """Show all parts"""
        for part_id in self.surfaces.keys():
            self.visibility_checkboxes[part_id].value = True

    def hide_all(self, button):
        """Hide all parts"""
        for part_id in self.surfaces.keys():
            self.visibility_checkboxes[part_id].value = False

    def reset_all(self, button):
        """Reset all settings to default"""
        for part_id, surface in self.surfaces.items():
            self.color_pickers[part_id].value = surface['color']
            self.opacity_sliders[part_id].value = surface['opacity']
            self.visibility_checkboxes[part_id].value = surface['visible']

    def apply_preset(self, preset_name):
        """Apply color presets"""

        presets = {
            'medical': {
                1: '#696969',  # Dim Gray
                2: '#F5F5F5',  # White Smoke
                3: '#4682B4'   # Steel Blue
            },
            'vibrant': {
                1: '#FF1493',  # Deep Pink
                2: '#00FF7F',  # Spring Green
                3: '#1E90FF'   # Dodger Blue
            },
            'pastel': {
                1: '#D3D3D3',  # Light Gray
                2: '#FFFAF0',  # Floral White
                3: '#B0E0E6'   # Powder Blue
            }
        }

        if preset_name in presets:
            for part_id, color in presets[preset_name].items():
                if part_id in self.surfaces:
                    self.color_pickers[part_id].value = color

    def display(self):
        """Display the controller and plot"""

        # Create layout with controller and plot side by side
        layout = widgets.HBox([
            self.control_panel,
            widgets.VBox([
                widgets.HTML("<h3>🎨 Real-time 3D Visualization</h3>"),
                self.fig
            ])
        ])

        display(layout)

        # Instructions
        instructions = widgets.HTML("""
        <div style='background-color: #f0f8ff; padding: 15px; border-radius: 10px; margin: 10px;'>
        <h4>🎮 How to Use the Interactive Controller:</h4>
        <ul>
        <li><b>Color:</b> Select different colors for each brain part from dropdown</li>
        <li><b>Opacity:</b> Adjust transparency (0 = transparent, 1 = opaque)</li>
        <li><b>Visibility:</b> Show/hide individual parts with checkboxes</li>
        <li><b>Global Controls:</b> Show all, hide all, or reset to defaults</li>
        <li><b>Presets:</b> Apply predefined color schemes</li>
        <li><b>3D Navigation:</b> Click and drag to rotate, scroll to zoom</li>
        </ul>
        </div>
        """)

        display(instructions)

# ============================================================================
# STEP 3: Advanced Visualization Options
# ============================================================================

def create_comparison_view(surfaces, save_dir):
    """Create side-by-side comparison views"""

    print("🔍 Creating comparison visualization...")

    # Create subplots
    fig = make_subplots(
        rows=2, cols=2,
        subplot_titles=('All Parts', 'Individual Parts', 'Cross-Section View', 'Statistics'),
        specs=[[{'type': 'scatter3d'}, {'type': 'scatter3d'}],
               [{'type': 'scatter3d'}, {'type': 'bar'}]],
        vertical_spacing=0.08,
        horizontal_spacing=0.05
    )

    # Plot 1: All parts together
    for part_id, surface in surfaces.items():
        vertices = surface['vertices']
        faces = surface['faces']

        fig.add_trace(
            go.Mesh3d(
                x=vertices[:, 0], y=vertices[:, 1], z=vertices[:, 2],
                i=faces[:, 0], j=faces[:, 1], k=faces[:, 2],
                name=surface['name'],
                color=surface['color'],
                opacity=0.7,
                showlegend=True
            ),
            row=1, col=1
        )

    # Plot 2: Individual parts
    for i, (part_id, surface) in enumerate(surfaces.items()):
        vertices = surface['vertices']
        faces = surface['faces']

        fig.add_trace(
            go.Mesh3d(
                x=vertices[:, 0], y=vertices[:, 1], z=vertices[:, 2],
                i=faces[:, 0], j=faces[:, 1], k=faces[:, 2],
                name=f"Solo {surface['name']}",
                color=surface['color'],
                opacity=0.9,
                visible=(i == 0),
                showlegend=False
            ),
            row=1, col=2
        )

    # Plot 3: Cross-section
    z_slice = brain_3parts.shape[2] // 2
    slice_data = brain_3parts[:, :, z_slice]

    for part_id, surface in surfaces.items():
        coords = np.where(slice_data == part_id)
        if len(coords[0]) > 0:
            sample_size = min(1000, len(coords[0]))
            indices = np.random.choice(len(coords[0]), sample_size, replace=False)

            fig.add_trace(
                go.Scatter3d(
                    x=coords[0][indices] * spacing[0],
                    y=coords[1][indices] * spacing[1],
                    z=np.full(sample_size, z_slice * spacing[2]),
                    mode='markers',
                    marker=dict(size=3, color=surface['color'], opacity=0.8),
                    name=f"Cross-section {surface['name']}",
                    showlegend=False
                ),
                row=2, col=1
            )

    # Plot 4: Volume statistics
    volumes = [surface['volume_cm3'] for surface in surfaces.values()]
    names = [surface['name'] for surface in surfaces.values()]
    colors_bar = [surface['color'] for surface in surfaces.values()]

    fig.add_trace(
        go.Bar(
            x=names,
            y=volumes,
            marker_color=colors_bar,
            name='Volume (cm³)',
            showlegend=False,
            text=[f"{v:.1f} cm³" for v in volumes],
            textposition='auto'
        ),
        row=2, col=2
    )

    # Update layout
    fig.update_layout(
        title="Comprehensive Brain Analysis Dashboard",
        height=800,
        scene=dict(aspectmode='data'),
        scene2=dict(aspectmode='data'),
        scene3=dict(aspectmode='data')
    )

    # Add buttons for cycling through individual parts
    part_buttons = []
    for i, (part_id, surface) in enumerate(surfaces.items()):
        visible_list = [True] * len(surfaces)
        visible_list.extend([False] * len(surfaces))
        visible_list[len(surfaces) + i] = True
        visible_list.extend([True] * (len(surfaces) * 2))

        part_buttons.append(
            dict(
                label=f"Show {surface['name']} Solo",
                method="update",
                args=[{"visible": visible_list}]
            )
        )

    fig.update_layout(
        updatemenus=[
            dict(
                type="dropdown",
                direction="down",
                showactive=True,
                x=0.7, y=1.0,
                buttons=part_buttons
            )
        ]
    )

    fig.show()
    fig.write_html(str(save_dir / 'brain_comparison_dashboard.html'))

    return fig

# ============================================================================
# STEP 4: Initialize and Display Interactive Controller
# ============================================================================

if hq_surfaces:
    print("\n🎛️ Initializing Interactive Control Panel...")

    # Create the controller
    brain_controller = BrainVisualizationController(hq_surfaces)

    # Display the interactive interface
    print("🎨 Launching Interactive Visualization Controller...")
    brain_controller.display()

    # Create comparison dashboard
    comparison_fig = create_comparison_view(hq_surfaces, directories['visualizations'])

    # Save the controller setup
    controller_settings = {
        'initial_colors': {str(k): v['color'] for k, v in hq_surfaces.items()},
        'initial_opacities': {str(k): v['opacity'] for k, v in hq_surfaces.items()},
        'part_volumes': {str(k): float(v['volume_cm3']) for k, v in hq_surfaces.items()},
        'surface_areas': {str(k): float(v['surface_area_cm2']) for k, v in hq_surfaces.items()}
    }

    with open(directories['results'] / 'controller_settings.json', 'w') as f:
        json.dump(controller_settings, f, indent=2)

    print(f"💾 Controller settings saved to: {directories['results'] / 'controller_settings.json'}")

    print(f"\n🎉 Part 5 Complete!")
    print(f"✅ Interactive control panel launched with full functionality")
    print(f"✅ Real-time color, opacity, and visibility controls")
    print(f"✅ Multiple visualization presets available")
    print(f"✅ Comparison dashboard created")
    print(f"💾 All settings and dashboards saved to: {directories['visualizations']}")

    # Display usage tips
    display(widgets.HTML("""
    <div style='background-color: #e6ffe6; padding: 15px; border-radius: 10px; margin: 20px 0;'>
    <h3>🎯 Interactive Features Available:</h3>
    <ul>
    <li><b>Real-time Controls:</b> Change colors, opacity, and visibility instantly</li>
    <li><b>Color Presets:</b> Medical, Vibrant, and Pastel color schemes</li>
    <li><b>3D Navigation:</b> Rotate, zoom, and pan the 3D model</li>
    <li><b>Individual Part Analysis:</b> Focus on specific brain regions</li>
    <li><b>Volume Information:</b> Hover over parts to see detailed metrics</li>
    <li><b>Export Options:</b> All visualizations saved as HTML files</li>
    </ul>
    <p><b>🎮 Try experimenting with different settings to explore your brain segmentation!</b></p>
    </div>
    """))

else:
    print("❌ No surface data available. Please run Part 4 first!")

print(f"\n🏁 Complete Brain Segmentation Pipeline Finished!")
print(f"📊 Summary of all generated files:")
print(f"   - 3D Interactive Controller: interactive_3part_brain.html")
print(f"   - Comparison Dashboard: brain_comparison_dashboard.html")
print(f"   - All numerical results: 3part_brain_results.json")
print(f"   - Controller settings: controller_settings.json")